# Numpy Array

In [1]:
import numpy as np
type(np.array(["vbhvh", 2, 3]))

numpy.ndarray

In [2]:
#Upcasting:

In [2]:
a=np.array([1, 2, 3.0])
a.shape

(3,)

In [3]:
#two dimensions

In [4]:
 a=np.array([[1, 2,2], [3, 4,3]])
a.shape

(2, 3)

In [5]:
#Minimum dimensions 2:

In [6]:
np.array([1, 2, 3], ndmin=5)

array([[[[[1, 2, 3]]]]])

In [7]:
#dtype

In [3]:
 np.array([1, 2, 3], dtype=float)

array([1., 2., 3.])

In [9]:
#Data-type consisting of more than one element:

In [12]:
x = np.array([(1,2),(3,4)],dtype=[('a','<f2'),('b','<f2')])
x

array([(1., 2.), (3., 4.)], dtype=[('a', '<f2'), ('b', '<f2')])

In [13]:
type(x[1][0])

numpy.float16

In [14]:
x['a']

array([1., 3.], dtype=float16)

In [15]:
x['b']

array([2., 4.], dtype=float16)

In [14]:

#Creating an array from sub-classes:

In [15]:
np.mat(np.array([[1, 2],[4,7]]))

matrix([[1, 2],
        [4, 7]])

In [16]:
np.mat('1 2 3; 3 4 4')

matrix([[1, 2, 3],
        [3, 4, 4]])

In [17]:
type(np.mat('1 2; 3 4'))

numpy.matrix

# numpy.asarray

In [19]:
#Convert a list into an array:

In [20]:
 a = [1, 2]
type(a)

list

In [21]:
type(np.asarray(a))

numpy.ndarray

In [22]:
a = np.array([1, 2]) #Existing arrays are not copied
type(a)

numpy.ndarray

In [20]:
np.asarray((1,2))
np.array((1,2))

array([1, 2])

In [24]:
#If dtype is set, array is copied only if dtype does not match:

In [25]:
a = np.array([1, 2], dtype=np.float32)
a

array([1., 2.], dtype=float32)

In [30]:
np.asarray([1,2]) is a

False

In [31]:
np.asarray([1,2])

array([1, 2])

In [32]:
np.asarray(a, dtype=np.float64) is a

False

In [33]:
# ndarray subclasses are not passed through

In [36]:
issubclass(np.matrix, np.ndarray)

True

# numpy.asanyarray

In [21]:
a = [1, 2]
b=np.asanyarray(a)
type(b)

numpy.ndarray

In [19]:
a = np.matrix([1, 2])
b=np.asanyarray(a)
c=np.asarray(a)
print(type(b))
print(type(c))

<class 'numpy.matrix'>
<class 'numpy.ndarray'>


In [39]:
np.asanyarray([1,2]) is a

False

# numpy.copy -Solo Copy

In [44]:
#Create an array x, with a reference y and a copy z:

In [26]:
x = np.array([1, 2, 3])
x

NameError: name 'z' is not defined

In [22]:
y=x
y

array([1, 2, 3])

In [27]:
y[0]=500
y
x

array([1, 2, 3])

In [28]:
y
x

array([1, 2, 3])

# Deep Copy

In [51]:
z = np.copy(x)

In [56]:
z

array([100,   2,   3])

In [58]:
z[0]=200
z

array([200,   2,   3])

In [59]:
x

array([100,   2,   3])

In [93]:
id(y)

4768156128

# numpy.fromfunction

In [58]:
#Construct an array by executing a function over each coordinate.

In [60]:
np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [61]:
np.fromfunction(lambda i, j: i * j, (3, 3), dtype=int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [62]:
#Create a new 1-dimensional array from an iterable object.

In [31]:
for i in range(10):
    print(i)
    
a=np.range(100)

0
1
2
3
4
5
6
7
8
9


AttributeError: module 'numpy' has no attribute 'range'

In [68]:
np.fromiter(range(10),int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
#A new 1-D array initialized from text data in a string

In [32]:
a = np.fromstring('234 234 Hari',sep=' ')
a

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  """Entry point for launching an IPython kernel.


array([234., 234.])

In [102]:
np.fromstring('1, 2', dtype=int, sep=',')

array([1, 2])

# data types

In [33]:
my_list = [1,2,3]
import numpy as np
arr = np.array(my_list)
print("Type/Class of this object:",type(arr))
print("Here is the vector\n--------------------\n",arr)

Type/Class of this object: <class 'numpy.ndarray'>
Here is the vector
--------------------
 [1 2 3]


In [34]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)
print("Type/Class of this object:",type(mat))
print("Here is the matrix\n----------\n",mat,"\n----------")
print("Dimension of this matrix: ",mat.ndim,sep='') #ndim gives the dimensison, 2 for a matrix, 1 for a vector
print("Size of this matrix: ", mat.size,sep='') #size gives the total number of elements
print("Shape of this matrix: ", mat.shape,sep='') #shape gives the number of elements along each axes (dimension)
print("Data type of this matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array


Type/Class of this object: <class 'numpy.ndarray'>
Here is the matrix
----------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
----------
Dimension of this matrix: 2
Size of this matrix: 9
Shape of this matrix: (3, 3)
Data type of this matrix: int32


In [28]:
my_mat = [[1.1,2,3],[4,5.2,6],[7,8.3,9]]
mat = np.array(my_mat)
print("Data type of the modified matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array
print("\n\nEven tuples can be converted to ndarrays...")


Data type of the modified matrix: float64


Even tuples can be converted to ndarrays...


In [29]:
b = np.array([(1.5,2,3), (4,5,6)])
print("We write b = np.array([(1.5,2,3), (4,5,6)])")
print("Matrix made from tuples, not lists\n---------------------------------------")
print(b)

We write b = np.array([(1.5,2,3), (4,5,6)])
Matrix made from tuples, not lists
---------------------------------------
[[1.5 2.  3. ]
 [4.  5.  6. ]]


# arange and linspace

In [38]:
a=range(10)
b=np.arange(1,5.998)
print (a)
print (b)

range(0, 10)
[1. 2. 3. 4. 5.]


In [39]:
print("A series of numbers:",type(np.arange(5,16)))
np.arange(5,16,2.3)# A series of numbers from low to high

A series of numbers: <class 'numpy.ndarray'>


array([ 5. ,  7.3,  9.6, 11.9, 14.2])

In [128]:
list(range(5,16,2))

[5, 7, 9, 11, 13, 15]

In [129]:
list(range(50,-1,5))

[]

In [135]:
print("Numbers spaced apart by 2:",np.arange(50,-1,5)) # Numbers spaced apart by 2

Numbers spaced apart by 2: []


In [131]:
print("Numbers spaced apart by float:",np.arange(0,11,2.5)) # Numbers spaced apart by 2.5

Numbers spaced apart by float: [ 0.   2.5  5.   7.5 10. ]


In [132]:
print("Every 5th number from 50 in reverse order\n",np.arange(5.0,-1,-5))

Every 5th number from 50 in reverse order
 [5. 0.]


In [35]:
print("21 linearly spaced numbers between 1 and 5\n--------------------------------------------")
print((np.linspace(1,5,20)))

21 linearly spaced numbers between 1 and 5
--------------------------------------------
[1.         1.21052632 1.42105263 1.63157895 1.84210526 2.05263158
 2.26315789 2.47368421 2.68421053 2.89473684 3.10526316 3.31578947
 3.52631579 3.73684211 3.94736842 4.15789474 4.36842105 4.57894737
 4.78947368 5.        ]


# Matrix creation

In [36]:
print("Vector of zeroes\n---------------------")
print(np.zeros(5))

Vector of zeroes
---------------------
[0. 0. 0. 0. 0.]


In [37]:
print("Matrix of zeroes\n--------------------")
print(np.zeros((3,4))) # Notice Tuples

Matrix of zeroes
--------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
print("Vector of ones\n---------------------")
print(np.ones(5))

Vector of ones
---------------------
[1. 1. 1. 1. 1.]


In [7]:
print("Matrix of ones\n---------------------")
print(7+np.ones((2,2,8))) # Note matrix dimension specified by Tuples

Matrix of ones
---------------------
[[[8. 8. 8. 8. 8. 8. 8. 8.]
  [8. 8. 8. 8. 8. 8. 8. 8.]]

 [[8. 8. 8. 8. 8. 8. 8. 8.]
  [8. 8. 8. 8. 8. 8. 8. 8.]]]


In [147]:
print("Matrix of 5's\n---------------------")
print(5+np.ones((3,5)))

Matrix of 5's
---------------------
[[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]


In [8]:
mat1 = np.eye(3)
print("Identity matrix of dimension", mat1.shape)
print(mat1)

Identity matrix of dimension (3, 3)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [132]:
np.arange(3)

array([0, 1, 2])

In [80]:
np.arange(3.0)

array([0., 1., 2.])

In [81]:
 np.arange(3,7)

array([3, 4, 5, 6])

In [82]:
np.arange(3,7,2)

array([3, 5])

In [9]:
np.linspace(2.0, 3.0, num=10)

array([2.        , 2.11111111, 2.22222222, 2.33333333, 2.44444444,
       2.55555556, 2.66666667, 2.77777778, 2.88888889, 3.        ])

In [10]:
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [11]:
np.linspace(2.0, 3.0, num=10, retstep=True)

(array([2.        , 2.11111111, 2.22222222, 2.33333333, 2.44444444,
        2.55555556, 2.66666667, 2.77777778, 2.88888889, 3.        ]),
 0.1111111111111111)

In [147]:
#Return numbers spaced evenly on a log scale.
np.linspace(2.0, 3.0, num=4)

array([2.        , 2.33333333, 2.66666667, 3.        ])

In [12]:
np.logspace(2.0, 3.0, num=4,base = 10)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [13]:
np.logspace(2.0, 3.0, num=10, endpoint=False)

array([100.        , 125.89254118, 158.48931925, 199.5262315 ,
       251.18864315, 316.22776602, 398.10717055, 501.18723363,
       630.95734448, 794.32823472])

In [14]:
np.logspace(2.0, 3.0, num=4, base=2.0)

array([4.        , 5.0396842 , 6.34960421, 8.        ])

In [18]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [25]:
x = np.arange(9).reshape((3,3))

In [26]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
np.diag(x)

array([0, 4, 8])

In [32]:
np.diag(x, k=5)

array([], dtype=int32)

In [10]:
np.diag(x, k=-1)

array([3, 7])

In [11]:
np.diag(np.diag(x))

array([[0, 0, 0],
       [0, 4, 0],
       [0, 0, 8]])

In [122]:
#Create a two-dimensional array with the flattened input as a diagonal.

In [33]:
np.diagflat([[1,2], [3,4],[5,6]])

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

In [124]:
np.diagflat([1,2], 1)

array([[0, 1, 0],
       [0, 0, 2],
       [0, 0, 0]])

In [125]:
#An array with ones at and below the given diagonal and zeros elsewhere.

In [13]:
np.tri(3, 5, 1, dtype=int)

array([[1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0]])

In [191]:
np.tri(3, 5,k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

In [128]:
#return a Lower triangle of an array.

In [205]:
np.tril([[1,2,3],[4,5,6],[7,8,9]], 0)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [130]:
#return Upper triangle of an array.

In [206]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], 1)

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0],
       [0, 0, 0]])

# Random number generation

In [14]:
print("Random number generation (from Uniform distribution)")
print(np.random.rand(2,3)) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 

Random number generation (from Uniform distribution)
[[0.97262482 0.71621553 0.09653435]
 [0.54450261 0.12878153 0.51799809]]


In [15]:
print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(4,3))

Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[ 0.91589671 -1.476101   -0.18362259]
 [ 2.28338894 -0.16026679  0.81439107]
 [ 0.72154862 -2.20772281  0.0553456 ]
 [-1.3753208   1.26247337 -1.97187767]]


In [16]:
print("Random integer vector:",np.random.randint(1,10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")


Random integer vector: 3

Random integer matrix


In [34]:
print(np.random.randint(1,100,(3,3))) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)
print("\n20 samples drawn from a dice throw:",np.random.randint(1,7,20)) # 20 samples drawn from a dice throw

[[22 64 43]
 [19 50 34]
 [ 4 94 96]]

20 samples drawn from a dice throw: [5 6 3 1 2 5 3 4 6 4 6 4 5 5 5 1 6 5 2 5]


# Reshaping

In [15]:
from numpy.random import randint as ri
a = ri(1,100,36)
print(a)
b = a.reshape(2,3,6)
b.
#c = a.reshape(7,-19878)
#c

[37 92 42 70 96 74 68 18 73 69 74 95  4 24 77 11 11 87 74  6  7 80 50  4
 90 86 22 25 98 20 14 74 14 67 97 16]


ValueError: cannot reshape array of size 36 into shape (1,3,6)

In [7]:
print ("Shape of a:", a.shape)
print ("Shape of b:", b.shape)



Shape of a: (36,)
Shape of b: (2, 3, 6)


In [8]:
print("\na looks like\n",'-'*20,"\n",a,"\n",'-'*20)
print("\nb looks like\n",'-'*20,"\n",b,"\n",'-'*20)
print("\nc looks like\n",'-'*20,"\n",c,"\n",'-'*20)



a looks like
 -------------------- 
 [28 62 99  8 82 88 77 47 28  2 69 56 87 39 71 48 66 89 64  6 57 12 69 32
 68 11 58 10 11 99 57 92 65 74 11 17] 
 --------------------

b looks like
 -------------------- 
 [[[28 62 99  8 82 88]
  [77 47 28  2 69 56]
  [87 39 71 48 66 89]]

 [[64  6 57 12 69 32]
  [68 11 58 10 11 99]
  [57 92 65 74 11 17]]] 
 --------------------


NameError: name 'c' is not defined

In [5]:
A = ri(1,100,10) # Vector of random interegrs
print("\nVector of random integers\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A))



Vector of random integers
 -------------------------------------------------- 
 [51 78 71 44 44 18 17 41 12 52]

Here is the sorted vector
 -------------------------------------------------- 
 [12 17 18 41 44 44 51 52 71 78]


In [43]:
M = ri(1,100,25).reshape(5,5) # Matrix of random interegrs
M
#print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M, kind='mergesort')) # Default axis =1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M, axis=1, kind='mergesort'))
M


Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[35 42 74 80 80]
 [20 53 67 76 76]
 [28 39 69 97 97]
 [ 2 24 55 59 67]
 [27 33 49 58 91]]


array([[74, 80, 80, 42, 35],
       [20, 76, 67, 53, 76],
       [69, 39, 97, 28, 97],
       [ 2, 59, 24, 55, 67],
       [91, 33, 49, 27, 58]])

In [11]:
print("Max of a:", a.max())
print("Max of b:", b.max())
b

Max of a: 99
Max of b: 99


array([[[28, 62, 99,  8, 82, 88],
        [77, 47, 28,  2, 69, 56],
        [87, 39, 71, 48, 66, 89]],

       [[64,  6, 57, 12, 69, 32],
        [68, 11, 58, 10, 11, 99],
        [57, 92, 65, 74, 11, 17]]])

In [12]:
M

NameError: name 'M' is not defined

In [14]:
#print("Max of a location:", M.argmax(axis= 1 ))
print("Max of b location:", b.argmax())
print("Max of c location:", b.argmax())

Max of b location: 2
Max of c location: 2


# Indexing and slicing

In [17]:
arr = np.arange(0,11)
print("Array:",arr)


Array: [ 0  1  2  3  4  5  6  7  8  9 10]


In [24]:
print("Element at 7th index is:", arr[7])


Element at 7th index is: 7


In [25]:
print("Elements from 3rd to 5th index are:", arr[3:10:2])


Elements from 3rd to 5th index are: [3 5 7 9]


In [231]:
print("Elements up to 4th index are:", arr[:4])
arr

Elements up to 4th index are: [0 1 2 3]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [233]:
print("Elements from last backwards are:", arr[-1:7:-1])


Elements from last backwards are: [10  9  8]


In [18]:
print("3 Elements from last backwards are:", arr[::-1])


3 Elements from last backwards are: [10  9  8  7  6  5  4  3  2  1  0]


In [165]:
arr = np.arange(0,21,2)
print("New array:",arr)


New array: [ 0  2  4  6  8 10 12 14 16 18 20]


In [64]:
print("Elements at 2nd, 4th, and 9th index are:", arr[[2,4,9]]) # Pass a list as a index to subset

Elements at 2nd, 4th, and 9th index are: [ 4  8 18]


# Subseting

In [22]:
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)
mat<80

Matrix of random 2-digit numbers
--------------------------------
 [[92 91 35 57 25]
 [45 86 23 84 67]
 [81 23 57 51 54]]


array([[False, False,  True,  True,  True],
       [ True, False,  True, False,  True],
       [False,  True,  True,  True,  True]])

In [23]:
print ("Elements greater than 50\n", mat[mat>50])

Elements greater than 50
 [92 91 57 86 84 67 81 57 51 54]


# Slicing

In [24]:
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)


Original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [26]:
mat_slice = mat[:2,:2]
print ("\nSliced matrix")
print(mat_slice)
print ("\nChange the sliced matrix")


Sliced matrix
[[11 12]
 [21 22]]

Change the sliced matrix


In [27]:
mat_slice[0,1]=1000
print (mat_slice)

[[  11 1000]
 [  21   22]]


In [39]:
print("\nBut the original matrix? WHOA! It got changed too!")
print(mat)



But the original matrix? WHOA! It got changed too!
[[11 12 13]
 [21 22 23]
 [31 32 33]]


# Universal Functions

In [247]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)



1st Matrix of random single-digit numbers
----------------------------------------
 [[3 3 9]
 [6 1 8]
 [5 9 1]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[3 5 7]
 [4 4 9]
 [1 2 5]]


In [248]:
mat1*mat2

array([[ 9, 15, 63],
       [24,  4, 72],
       [ 5, 18,  5]])

In [249]:
#print("\nAddition\n------------------\n", mat1+mat2)
print("\nMultiplication\n------------------\n", mat1@mat2)




Multiplication
------------------
 [[ 30  45  93]
 [ 30  50  91]
 [ 52  63 121]]


In [251]:
print("\nDivision\n------------------\n", mat1/0)
#print("\nLineaer combination: 3*A - 2*B\n-----------------------------\n", 3*mat1-2*mat2)



Division
------------------
 [[inf inf inf]
 [inf inf inf]
 [inf inf inf]]


/Users/sudhanshukumar/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


In [252]:
print("\nAddition of a scalar (100)\n-------------------------\n", 100+mat1)



Addition of a scalar (100)
-------------------------
 [[103 103 109]
 [106 101 108]
 [105 109 101]]


In [253]:
print("\nExponentiation, matrix cubed here\n----------------------------------------\n", mat1**3)
print("\nExponentiation, sq-root using pow function\n-------------------------------------------\n",pow(mat1,3))


Exponentiation, matrix cubed here
----------------------------------------
 [[ 27  27 729]
 [216   1 512]
 [125 729   1]]

Exponentiation, sq-root using pow function
-------------------------------------------
 [[ 27  27 729]
 [216   1 512]
 [125 729   1]]


# Broadcasting

In [174]:
#NumPy operations are usually done on pairs of arrays on an element-by-element basis. 
#In the simplest case, the two arrays must have exactly the same shape.
#NumPy’s broadcasting rule relaxes this constraint when the arrays’ shapes meet certain constraints. 
#When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing 
#dimensions, and works its way forward. Two dimensions are compatible when
#they are equal, or one of them is 1

In [254]:
start = np.zeros((4,4))
start= start+100
start

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.]])

In [256]:
# create a rank 1 ndarray with 3 values
add_rows = np.array([1, 0, 2,5])
print(add_rows)

[1 0 2 5]


In [257]:
y = start + add_rows  # add to each row of 'start' using broadcasting
print(y)

[[101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]]


In [28]:
# create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3,9]])
add_cols = add_cols.T
print(add_cols)

[[0]
 [1]
 [2]
 [3]
 [9]]


In [263]:
# add to each column of 'start' using broadcasting
y = start + add_cols 
print(y)

[[100. 100. 100. 100.]
 [101. 101. 101. 101.]
 [102. 102. 102. 102.]
 [103. 103. 103. 103.]]


In [264]:
# this will just broadcast in both dimensions
add_scalar = np.array([100])  
print(start+y)

[[200. 200. 200. 200.]
 [201. 201. 201. 201.]
 [202. 202. 202. 202.]
 [203. 203. 203. 203.]]


# Array Math

In [265]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n------------\n",mat2)



1st Matrix of random single-digit numbers

 [[9 5 4]
 [1 7 3]
 [8 3 5]]

2nd Matrix of random single-digit numbers
------------
 [[4 8 6]
 [7 6 8]
 [4 6 5]]


In [266]:
print("\nSq-root of 1st matrix using np\n------------------\n", np.sqrt(mat1))



Sq-root of 1st matrix using np
------------------
 [[3.         2.23606798 2.        ]
 [1.         2.64575131 1.73205081]
 [2.82842712 1.73205081 2.23606798]]


In [267]:
print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", np.exp(mat1))



Exponential power of 1st matrix using np
 -------------------------------------------------- 
 [[8.10308393e+03 1.48413159e+02 5.45981500e+01]
 [2.71828183e+00 1.09663316e+03 2.00855369e+01]
 [2.98095799e+03 2.00855369e+01 1.48413159e+02]]


In [268]:
print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", np.log10(mat1))
print(mat1)
print(mat2)


10-base logarithm on 1st matrix using np
 -------------------------------------------------- 
 [[0.95424251 0.69897    0.60205999]
 [0.         0.84509804 0.47712125]
 [0.90308999 0.47712125 0.69897   ]]
[[9 5 4]
 [1 7 3]
 [8 3 5]]
[[4 8 6]
 [7 6 8]
 [4 6 5]]


In [270]:
print("\nModulo reminder using np\n",'-'*50,"\n", np.fmod(mat1,mat2))
mat1%mat2


Modulo reminder using np
 -------------------------------------------------- 
 [[1 5 4]
 [1 1 3]
 [0 3 0]]


array([[1, 5, 4],
       [1, 1, 3],
       [0, 3, 0]])

In [186]:
print("\nCombination of functions by shwoing exponetial decay of a sine wave\n",'-'*70)



Combination of functions by shwoing exponetial decay of a sine wave
 ----------------------------------------------------------------------


In [207]:
A = np.linspace(0,12*np.pi,1001)


In [208]:
A

array([ 0.        ,  0.03769911,  0.07539822, ..., 37.62371362,
       37.66141273, 37.69911184])